### ISSUE TITLE
Trouble understanding how to get image sizing to work

### ISSUE THREAD

**Issue by sciascia** [jordanlev/c5_designer_gallery#4]
Hey Jordan,

I'm trying to get the image sizing to work and so far have the following set in controller.php:

``` php
//Default values for new blocks...
private $defaultLargeWidth = 880;
private $defaultLargeHeight = 0;
private $defaultCropLarge = false;
private $defaultThumbWidth = 80;
private $defaultThumbHeight = 0;
private $defaultCropThumb = false;
private $defaultRandomize = false;

//Add/Edit interface configuration...
private $showLargeControls = false;
private $showThumbControls = false;
```

And then the following in the view template:

``` php
<?php foreach ($images as $img_preview): ?>
  <img src="<?php echo $img_preview->large->src; ?>" width="520" height="280" alt="<?php echo $img_preview->title; ?>" />
  <div class="gallery-description">
    <?php echo $img_preview->description; ?>
  </div>
<?php break; endforeach; ?>
```

``` php
<?php foreach ($images as $img): ?>
  <li>
    <a href="<?php echo $img->thumb->src; ?>" width="80" height="50" alt="<?php echo $img->title; ?>">
      <img src="<?php echo $img->large->src ?>" alt="<?php echo $img->title; ?>" />
    </a>
    <span class="hidden"><?php echo $img->description; ?></span>
  </li>
<?php endforeach; ?>
```

But all the images get output at their original size of: 1200 x 600 (obviously the browser resizes them to the size in the html img tag). I also tried clearing the cache and deleting/adding a new gallery block to check if those settings only get applied to new instances of the block.

Sorry if I've misunderstood how to set that up - but can you see what I might be doing wrong?

Cheers

Ben

**Comment by sciascia** [comment]
Sorry dude, I've gone over this a fair few times but just can't seem to figure out what I'm doing wrong sorry - any pointers would be awesome. Might just start again with a fresh download.

Cheers

Ben

**Comment by jordanlev** [comment]
Hi Ben,
Sorry for the delay. If you look at your code, you'll see that you have some "hard-coded" width and height attributes. I wonder if those are overriding the actual image size itself and constraining the proportions? For example, you have this line:
`<img src="<?php echo $img_preview->large->src; ?>" width="520" height="280" alt="<?php echo $img_preview->title; ?>" />`
...and then this one:
`<a href="<?php echo $img->thumb->src; ?>" width="80" height="50" alt="<?php echo $img->title; ?>">`

Try changing those to be the width and height of the image itself (for example, `<?php echo $img->thumb->width; ?>`).

**Comment by sciascia** [comment]
Thanks mate, yes, I removed those but I could see in Firebug that c5 was outputting the full 1200x600 image - I ended up deleting the package re-download and installing the latest version and now the images are resizing.

Cheers
