### ISSUE TITLE
$img->LinkUrl not working 5.6.1.2?

### ISSUE THREAD

**Issue by ecomatt** [jordanlev/c5_designer_gallery#5]
Hi there i have tried to implement the LinkUrl part of the designer gallery block but it does not work.
in the view.php i have this 

![screen shot 2013-06-29 at 15 00 49](https://f.cloud.github.com/assets/4817247/726029/6c9652c6-e0c4-11e2-822c-dc8b4501563b.png)

I have the page attribute installed and i add a page i want the image to link to but in the page source all i see is a href="" witch is blank, so not sure why its not working?

can you help at all please.
the site is located here http://gransmore.co.uk.gridhosted.co.uk/index.php
Thanks

**Comment by jordanlev** [comment]
You've got the capitalization wrong. It's linkUrl (lowercase "l"), not LinkUrl.

  -Jordan

**Comment by ecomatt** [comment]
Thank you so much for your swift response i got that from the documentation which says:
-   $img->LinkUrl : URL of a page that the image should link to when clicked (NOTE THAT THIS DOES NOT WORK OUT OF THE BOX -- SEE DOCUMENTATION FOR HOW TO SET THIS UP ON YOUR SITE)

Thanks again it now works like a charm
I love this plugin so much its allowed me to create some great bespoke slideshows and now page filters.

I also wanted to ask can i easily create different templates by adding a folder in a template folder?
Then can i have css js folders as well as a variant view.php in that template folder? 
Or does the view.php have to load form the master block folder?

thanks again

**Comment by jordanlev** [comment]
Thanks for pointing out the typo -- I've fixed that in the code comments.

And yes, you should be able to make custom templates for this just like any other block.
